import { db } from "./server/db";
import { workouts } from "./db/schema";
import { eq } from "drizzle-orm";

async function checkSchema() {
  try {
    // Try to insert a test workout with new fields
    const testWorkout = await db.insert(workouts).values({
      name: "Test AI Workout",
      description: "Testing new fields",
      userId: "test-user",
      createdBy: "ai-agent",
      autoGenerated: true,
      metadata: { test: true },
      estimatedCalories: 300,
      tags: ["test", "ai"],
      targetMuscleGroups: ["chest", "arms"],
      analytics: { timesCompleted: 0 }
    }).returning();
    
    console.log("✅ New fields working:", testWorkout);
    
    // Clean up
    await db.delete(workouts).where(eq(workouts.id, testWorkout[0].id));
  } catch (error) {
    console.error("❌ Schema issue:", error);
  }
}

checkSchema();